"""empty message

Revision ID: 066a088c3d80
Revises: d0e24f02b4f7
Create Date: 2020-06-04 18:57:02.676212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '066a088c3d80'
down_revision = 'd0e24f02b4f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('visbility', sa.Boolean(), nullable=True))
    op.drop_constraint('event_ibfk_1', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'user', ['user_id'], ['id'])
    op.drop_column('event', 'creator')
    op.drop_column('user', 'visbility')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('visbility', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('creator', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('event_ibfk_1', 'event', 'user', ['creator'], ['id'])
    op.drop_column('event', 'visbility')
    op.drop_column('event', 'user_id')
    # ### end Alembic commands ###
