"""empty message

Revision ID: 8f8c9783765c
Revises: 
Create Date: 2020-06-06 01:24:49.349365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f8c9783765c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('visbility', sa.Boolean(), nullable=False))
    op.alter_column('event', 'cost',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint('event_ibfk_1', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'user', ['user_id'], ['id'])
    op.drop_column('event', 'creator')
    op.drop_column('event', 'name')
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=False))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=140),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=140),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('user', 'admin')
    op.add_column('event', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('event', sa.Column('creator', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('event_ibfk_1', 'event', 'user', ['creator'], ['id'])
    op.alter_column('event', 'cost',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('event', 'visbility')
    op.drop_column('event', 'user_id')
    # ### end Alembic commands ###
